server:
  port: ${PORT:${SERVERS_PORT:0}}

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8090/eureka
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    #hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-auth-service
          uri: lb://ms-auth
          predicates:
            - Path=/auth/**

        - id: ms-categoria-service
          uri: lb://ms-categoria
          predicates:
            - Path=/categorias/**
          filters:
            - AuthFilter

        - id: ms-cliente-service
          uri: lb://ms-cliente
          predicates:
            - Path=/clientes/**
          filters:
            - AuthFilter

        - id: ms-inventario-service
          uri: lb://ms-inventario
          predicates:
            - Path=/api/stock/**
          filters:
            - AuthFilter


        - id: ms-producto-service
          uri: lb://ms-producto
          predicates:
            - Path=/productos/**
          filters:
            - AuthFilter


        - id: ms-venta-service
          uri: lb://ms-venta
          predicates:
            - Path=/api/ventas/**
          filters:
            - AuthFilter
